name: Pruebas unitarias y funcionales

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Cargar esquema de la base de datos
        run: |
          psql -h localhost -U postgres -d testdb -f scripts.sql
        env:
          PGPASSWORD: postgres

      - name: Run tests
        run: |
          psql -h localhost -U postgres -d testdb -f tests.sql
        env:
          PGPASSWORD: postgres

      - name: Notify status
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKE }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          STATUS="failure"
          COMMENT="El estado de las pruebas es: $STATUS\nBranch: $GITHUB_REF\nUsuario: $GITHUB_ACTOR\nCommit: $GITHUB_SHA"

          curl -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
          -d "{\"body\": \"$COMMENT\"}"

      - name: Notify success
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          STATUS="success"
          COMMENT="El estado de las pruebas es: $STATUS\nBranch: $GITHUB_REF\nUsuario: $GITHUB_ACTOR\nCommit: $GITHUB_SHA"

          curl -X POST -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/1/comments \
          -d "{\"body\": \"$COMMENT\"}"